#!/usr/bin/env python3
"""Extract floor-plan geometry from L1007_mattsatt_planritning.pdf into data/plan.json.

Stdlib only. The PDF is vector (generated by ReportLab), so walls, windows, doors,
fixtures and labels can be read straight from the page content streams.

Coordinate system of the output (metres):
  x = east  (0 = outside face of the west exterior wall)
  z = south (0 = outside face of the entrance/north exterior wall, grows toward the patio)
"""
import base64
import json
import math
import re
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PDF = ROOT / "L1007_mattsatt_planritning.pdf"
OUT = ROOT / "data" / "plan.json"

WALL = (0.141, 0.216, 0.263)     # dark fill used for walls
CABINET = (0.929, 0.945, 0.953)  # light fill used for fixed cabinets
GREY = (0.404, 0.467, 0.502)     # door swings, sliding doors, fixture outlines
LIGHT = (0.773, 0.831, 0.863)    # dimension extension lines, shower outline
WHITE = (1.0, 1.0, 1.0)

# Per page: name, scale (pt per metre from the scale bar), and the PDF point of the
# outer north-west corner of the building.
PAGES = [
    dict(name="Entréplan", obj=16),
    dict(name="Övre plan", obj=17),
]


def rgb(v):
    return tuple(round(x, 3) for x in v)


def read_objects(data):
    objs = {}
    for m in re.finditer(rb"(?m)^(\d+) 0 obj", data):
        objs[int(m.group(1))] = m.start()
    return objs


def stream(data, objs, num):
    start = objs[num]
    head_end = data.find(b"stream", start)
    header = data[start:head_end]
    s = head_end + len(b"stream")
    while data[s:s + 1] in b"\r\n":
        s += 1
    e = data.find(b"endstream", s)
    raw = data[s:e].strip()
    if b"ASCII85Decode" in header:
        if raw.endswith(b"~>"):
            raw = raw[:-2]
        raw = base64.a85decode(raw)
    if b"FlateDecode" in header:
        raw = zlib.decompress(raw)
    return raw


def parse_cmap(text):
    """bfchar/bfrange ToUnicode cmap → {code: str}."""
    out = {}
    for block in re.findall(r"beginbfchar(.*?)endbfchar", text, re.S):
        for a, b in re.findall(r"<([0-9a-fA-F]+)>\s*<([0-9a-fA-F]+)>", block):
            out[int(a, 16)] = bytes.fromhex(b).decode("utf-16-be")
    for block in re.findall(r"beginbfrange(.*?)endbfrange", text, re.S):
        for a, b, c in re.findall(r"<([0-9a-fA-F]+)>\s*<([0-9a-fA-F]+)>\s*<([0-9a-fA-F]+)>", block):
            base = int(c, 16)
            for i, code in enumerate(range(int(a, 16), int(b, 16) + 1)):
                out[code] = chr(base + i)
    return out


def font_maps(data, objs):
    maps = {}
    for m in re.finditer(rb"/Name /(\S+) /Subtype /TrueType\s*/ToUnicode (\d+) 0 R", data):
        maps[m.group(1).decode()] = parse_cmap(stream(data, objs, int(m.group(2))).decode("latin1"))
    return maps


def pdf_string(s):
    """Decode a PDF literal string body (octal escapes) to raw byte values."""
    out, i = [], 0
    while i < len(s):
        ch = s[i]
        if ch == "\\":
            nxt = s[i + 1]
            if nxt.isdigit():
                j = i + 1
                while j < len(s) and j < i + 4 and s[j].isdigit():
                    j += 1
                out.append(int(s[i + 1:j], 8))
                i = j
                continue
            out.append(ord({"n": "\n", "r": "\r", "t": "\t"}.get(nxt, nxt)))
            i += 2
            continue
        out.append(ord(ch))
        i += 1
    return out


def parse_page(content, fmaps):
    texts = []
    for m in re.finditer(r"BT 1 0 0 1 ([-\d.]+) ([-\d.]+) Tm /(\S+) ([\d.]+) Tf [\d.]+ TL \((.*?)\) Tj T\* ET", content):
        cmap = fmaps.get(m.group(3), {})
        s = "".join(cmap.get(c, chr(c)) for c in pdf_string(m.group(5)))
        texts.append(dict(x=float(m.group(1)), y=float(m.group(2)), size=float(m.group(4)), text=s))
    body = re.sub(r"BT.*?ET", "", content, flags=re.S)

    toks = re.findall(r"\[[^\]]*\]|[-\d.]+|[A-Za-z*]+", body)
    st, fill, stroke, lw, dash = [], None, None, 1.0, False
    paths, cur, sub, ctm_offset = [], [], None, (0.0, 0.0)
    for k in toks:
        if re.match(r"^[-\d.]+$", k):
            st.append(float(k))
            continue
        if k.startswith("["):
            st.append(k)
            continue
        if k == "rg":
            fill = rgb(st[-3:])
        elif k == "RG":
            stroke = rgb(st[-3:])
        elif k == "w":
            lw = st[-1]
        elif k == "d":
            dash = st[-2] != "[]"
        elif k == "cm":
            ctm_offset = (st[-2], st[-1])
        elif k == "q":
            pass
        elif k == "Q":
            ctm_offset = (0.0, 0.0)
        elif k == "m":
            sub = [(st[-2], st[-1])]
            cur.append(dict(pts=sub, curve=False))
        elif k == "l":
            sub.append((st[-2], st[-1]))
        elif k == "c":
            sub.append((st[-2], st[-1]))
            cur[-1]["curve"] = True
        elif k == "re":
            x, y, w, h = st[-4:]
            cur.append(dict(pts=[(x, y), (x + w, y), (x + w, y + h), (x, y + h)], curve=False))
        elif k in ("f", "f*", "S", "B", "B*", "b", "s", "n"):
            if cur and k != "n" and ctm_offset == (0.0, 0.0):
                paths.append(dict(op=k, fill=fill, stroke=stroke, lw=lw, dash=dash, subs=cur))
            cur = []
        st = []
    return paths, texts


def bbox(pts):
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    return min(xs), min(ys), max(xs), max(ys)


def inside(pt, poly):
    x, y = pt
    c = False
    for i in range(len(poly)):
        (x1, y1), (x2, y2) = poly[i], poly[i - 1]
        if (y1 > y) != (y2 > y) and x < (x2 - x1) * (y - y1) / (y2 - y1) + x1:
            c = not c
    return c


def dedupe(pts):
    out = []
    for p in pts:
        if not out or math.dist(p, out[-1]) > 0.05:
            out.append(p)
    if len(out) > 1 and math.dist(out[0], out[-1]) < 0.05:
        out.pop()
    return out


def near(a, b, tol=0.6):
    return math.dist(a, b) < tol


def extract(page, paths, texts):
    walls = [p for p in paths if p["op"] == "f*" and p["fill"] == WALL]
    # Building outline: bounding box of all wall polygons (exterior walls are outermost).
    # (ignore the 1 pt slivers ReportLab draws at the façade corners)
    allpts = [pt for p in walls for s in p["subs"] for pt in s["pts"]
              if min(bbox(s["pts"])[2] - bbox(s["pts"])[0], bbox(s["pts"])[3] - bbox(s["pts"])[1]) > 2]
    x0, y0, x1, y1 = bbox(allpts)
    # Scale bar: the dark 1 m segment of the bar (B*, dark fill) near the bottom right.
    bar = [p for p in paths if p["op"] == "B*" and p["fill"] == WALL]
    bx0, _, bx1, _ = bbox(bar[0]["subs"][0]["pts"])
    scale = bx1 - bx0  # pt per metre

    def M(pt):
        return [round((pt[0] - x0) / scale, 4), round((y1 - pt[1]) / scale, 4)]

    def R(pts):
        a, b, c, d = bbox(pts)
        return dict(x0=round((a - x0) / scale, 4), x1=round((c - x0) / scale, 4),
                    z0=round((y1 - d) / scale, 4), z1=round((y1 - b) / scale, 4))

    # --- walls (each subpath is a polygon; contained subpaths are holes) ---
    polys = [dedupe(s["pts"]) for p in walls for s in p["subs"]]
    polys = [p for p in polys if len(p) >= 3
             and min(bbox(p)[2] - bbox(p)[0], bbox(p)[3] - bbox(p)[1]) > 2]
    def is_hole(h, poly):
        # strictly inside: neighbouring walls share edges with each other, holes don't
        a, b = bbox(h), bbox(poly)
        return (a[0] > b[0] + 0.5 and a[1] > b[1] + 0.5 and a[2] < b[2] - 0.5 and a[3] < b[3] - 0.5
                and inside(((a[0] + a[2]) / 2, (a[1] + a[3]) / 2), poly))

    wall_out = []
    for i, poly in enumerate(polys):
        if any(j != i and is_hole(poly, polys[j]) for j in range(len(polys))):
            continue
        holes = [[M(pt) for pt in h] for j, h in enumerate(polys) if j != i and is_hole(h, poly)]
        wall_out.append(dict(outer=[M(pt) for pt in poly], holes=holes))

    # --- doors: swing arcs + leaf lines ---
    arcs = [p for p in paths if p["op"] == "S" and p["stroke"] == GREY and p["lw"] == 0.5
            and len(p["subs"][0]["pts"]) > 20]
    # leaf = straight dark line from the hinge; dashed arc + dashed leaf = optional door (tillval)
    leaves = [p for p in paths if p["op"] == "S" and p["stroke"] == WALL and p["lw"] == 0.7
              and len(p["subs"][0]["pts"]) == 2]
    doors = []
    for a in arcs:
        apts = a["subs"][0]["pts"]
        wall_pt, tip = apts[0], apts[-1]
        for lf in leaves:
            h, t = lf["subs"][0]["pts"]
            if lf["dash"] == a["dash"] and (near(t, tip) or near(h, tip)):
                hinge = h if near(t, tip) else t
                doors.append(dict(hinge=M(hinge), tip=M(tip), wall=M(wall_pt), optional=a["dash"]))
                break
    # sliding doors: dashed grey straight line across a wall gap
    # and an arrow next to it (shaft + two head strokes sharing the head point) telling
    # which face the panel runs on and which way it opens.
    lines = [p["subs"][0]["pts"] for p in paths if p["op"] == "S" and p["stroke"] == GREY
             and not p["dash"] and len(p["subs"][0]["pts"]) == 2]
    arrows = []
    for shaft in lines:
        for head, tail in ((shaft[0], shaft[1]), (shaft[1], shaft[0])):
            n = sum(1 for l in lines if l is not shaft and (near(l[0], head, 0.2) or near(l[1], head, 0.2)))
            if n >= 2 and math.dist(head, tail) > 10:
                arrows.append((head, tail))
    sliding = []
    for p in paths:
        if p["op"] == "S" and p["stroke"] == GREY and p["dash"] and len(p["subs"][0]["pts"]) == 2:
            a, b = p["subs"][0]["pts"]
            mid = ((a[0] + b[0]) / 2, (a[1] + b[1]) / 2)
            entry = dict(a=M(a), b=M(b))
            if arrows:
                head, tail = min(arrows, key=lambda ar: math.dist(mid, ar[0]))
                entry["arrow"] = dict(head=M(head), tail=M(tail))
            sliding.append(entry)

    # --- windows & glazed door frames (white rects with dark outline, lw 0.65) ---
    windows, door_frames = [], []
    for p in paths:
        if p["op"] == "B*" and p["fill"] == WHITE and p["stroke"] == WALL and p["lw"] == 0.65:
            r = R(p["subs"][0]["pts"])
            depth = min(r["x1"] - r["x0"], r["z1"] - r["z0"])
            (windows if depth > 0.3 else door_frames).append(r)

    # --- fixed cabinets ---
    def label_in(r):
        for t in texts:
            tx, tz = (t["x"] + 3 - x0) / scale, (y1 - t["y"] - 2) / scale
            if t["size"] < 8 and r["x0"] <= tx <= r["x1"] and r["z0"] <= tz <= r["z1"]:
                return t["text"]
        return None

    cabinets = []
    for p in paths:
        if p["op"] == "B*" and p["fill"] == CABINET:
            r = R(p["subs"][0]["pts"])
            r["label"] = label_in(r)
            cabinets.append(r)

    # --- sanitary fixtures, sinks, hob, shower, stair outline ---
    fixtures = []
    stair = None
    for p in paths:
        s0 = p["subs"][0]
        if p["op"] == "B*" and p["fill"] == WHITE and p["stroke"] == WALL and p["lw"] == 0.8:
            stair = R(s0["pts"])
        elif p["op"] == "B*" and p["fill"] == WHITE and p["stroke"] == GREY and s0["curve"]:
            fixtures.append(dict(kind="toilet_bowl", **R(s0["pts"])))
        elif p["op"] == "B*" and p["fill"] == WHITE and p["stroke"] == WALL and p["lw"] == 0.6:
            r = R(s0["pts"])
            w, d = r["x1"] - r["x0"], r["z1"] - r["z0"]
            fixtures.append(dict(kind="toilet_tank" if min(w, d) < 0.2 else "sink", **r))
        elif p["op"] == "B*" and p["fill"] == WHITE and p["stroke"] == LIGHT and p["lw"] == 0.6:
            fixtures.append(dict(kind="shower", **R(s0["pts"])))
    W, D = (x1 - x0) / scale, (y1 - y0) / scale
    fixtures = [f for f in fixtures if f["x1"] < W + 0.5 and f["z1"] < D + 0.5]
    hob = [p for p in paths if p["op"] == "S" and p["stroke"] == GREY and p["subs"][0]["curve"]
           and len(p["subs"][0]["pts"]) == 5]
    if hob:
        pts = [pt for p in hob for pt in p["subs"][0]["pts"]]
        fixtures.append(dict(kind="hob", **R(pts)))

    # --- site elements (patio, hedge, fences) ---
    site = {}
    for p in paths:
        s0 = p["subs"][0]
        if p["op"] == "f*" and p["fill"] == (0.98, 0.984, 0.973):
            site["patio"] = R(s0["pts"])
        elif p["op"] == "B*" and p["fill"] == (0.918, 0.945, 0.902):
            site["hedge"] = R(s0["pts"])
        elif p["op"] == "S" and p["stroke"] == GREY and p["lw"] == 1.3:
            site.setdefault("fences", []).append(dict(a=M(s0["pts"][0]), b=M(s0["pts"][1])))

    # --- room labels (≥ 9 pt, inside the building) + area lines ---
    rooms = []
    for t in texts:
        tx, tz = (t["x"] - x0) / scale, (y1 - t["y"]) / scale
        if (t["size"] >= 10 or t["text"] == "Klk") and "m²" not in t["text"] and -1 < tx < (x1 - x0) / scale + 1 and -1 < tz < (y1 - y0) / scale + 5:
            rooms.append(dict(name=t["text"], x=round(tx, 3), z=round(tz, 3)))
    for t in texts:
        if "m²" in t["text"]:
            tx, tz = (t["x"] - x0) / scale, (y1 - t["y"]) / scale
            best = min(rooms, key=lambda r: math.hypot(r["x"] - tx, r["z"] - tz), default=None)
            if best and math.hypot(best["x"] - tx, best["z"] - tz) < 1.5 and "area" not in best:
                best["area"] = t["text"]
    rooms = [r for r in rooms if "area" in r or r["name"] in ("Hall", "Klk", "WC / dusch")]

    return dict(
        name=page["name"],
        scale_pt_per_m=round(scale, 3),
        size=dict(x=round((x1 - x0) / scale, 3), z=round((y1 - y0) / scale, 3)),
        walls=wall_out, windows=windows, door_frames=door_frames, doors=doors, sliding=sliding,
        cabinets=cabinets, fixtures=fixtures, stair=stair, rooms=rooms, site=site,
    )


def main():
    data = PDF.read_bytes()
    objs = read_objects(data)
    fmaps = font_maps(data, objs)
    floors = []
    for page in PAGES:
        content = stream(data, objs, page["obj"]).decode("latin1")
        paths, texts = parse_page(content, fmaps)
        floors.append(extract(page, paths, texts))
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps(dict(source=PDF.name, floors=floors), ensure_ascii=False, indent=1))
    for f in floors:
        print(f"{f['name']}: {f['size']} m, {len(f['walls'])} walls, {len(f['windows'])} windows, "
              f"{len(f['doors'])} doors, {len(f['sliding'])} sliding, {len(f['cabinets'])} cabinets, "
              f"{len(f['fixtures'])} fixtures, rooms={[r['name'] for r in f['rooms']]}", file=sys.stderr)


if __name__ == "__main__":
    main()
